### PR TITLE
Add Orca support

### PR DESCRIPTION
**Pull request by felipeZ**
## Changes
* Solve #10 by allowing to call Orca as DFT engine
* Introduce a XML editor
* Add test for XTP class

### CODE REVIEW

**Comment by baumeier** [comment]
@felipeZ Can you give an example how changing options is now supposed to work? 
`votca.options['basisset']='cc-pvtz'` works as before but if I want to change, say, the GWBSE `mode` further down the tree, something like 
```
votca.options['gwbse_engine.gwbse_options.gwbse.mode']='G0W0'
```
fails by putting it here:
```
<dftgwbse help="Compute electronic excitations using GW-BSE">
    <gwbse_engine.gwbse_options.gwbse.mode>G0W0</gwbse_engine.gwbse_options.gwbse.mode><optimize help="Perform a molecular geometry optimization" default="false" choices="bool" />
    <basisset help="Basis set for MOs" default="def2-tzvp">cc-pvtz</basisset>
```

**Comment by felipeZ** [comment]
@baumeier  the problem is the syntax that you are using, you should provide the key as follow:
```py
votca.options["gwbse_engine"]["gwbse_options"]["gwbse.mode"]='G0W0'
```

If you prefer I can introduce the following notation too:
```py
votca.options.gwbse_engine.gwbse_options.gwbse.mode ='G0W0'
```
The only problem with the last notation is that if the keyword has spaces it doesn't work

**Comment by baumeier** [comment]
@felipeZ OK, that means that the user needs to know the full tree element to change something that is not on the upper `dftgwbse` level, like `basisset`.

I think it would be good then to define a few functions that take this burden away from the user for the more common options. Something like 
```
votca.setGWBSEmode('G0W0)
```
?

**Comment by felipeZ** [comment]
> @felipeZ OK, that means that the user needs to know the full tree element to change something that is not on the upper `dftgwbse` level, like `basisset`.
> 
> I think it would be good then to define a few functions that take this burden away from the user for the more common options. Something like
> 
> ```
> votca.setGWBSEmode('G0W0')
> ```
> 
> ?

Sure, we can introduce those helper functions for the most common functionality

**Comment by felipeZ** [comment]
@baumeier  see [example about new notation](https://github.com/votca/PyVOTCA/blob/orca/examples/run_votca.py#L21)

**Review by baumeier — APPROVED** [review]

**Pull request merged**
