### PR TITLE
remove the permutations calculations out of get_grad

### LINKED ISSUE #29: Move the permutation calculation out of the get_gradient method
## Changes
* Don't compute the permutations every time that the `get_gradient` is called.
* Show how to call the `run_perm` method in the examples

### PR DESCRIPTION
**Pull request by felipeZ**
fix #29

### CODE REVIEW

**Comment by felipeZ** [comment]
@baumeier @gtirimbo  do you know why the `electron_phonon` test is failing?

**Comment by baumeier** [comment]
oh, I think when I changed the behavior of calculating the vib frequencies (throwing out anything <10cm^-1), this has changed the results, obviously. Forgot to take care of the test

**Comment by felipeZ** [comment]
@baumeier  shall we merge this one?

**Comment by baumeier** [comment]
@felipeZ Yes, for the failing test, we need to update the reference data.

**Pull request merged**
